config/routes.rb
Rails.application.routes.draw do

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]

  resources :cats
  resources :cat_rental_requests, only: [:index, :new, :create] do
    patch 'approve'
    patch 'deny'
  end

end

app/models/cat.rb
class Cat < ActiveRecord::Base
  validates :birth_date, :color, :name, :sex, presence: true
  validates :sex, inclusion: { in: %w(M F), message: "%{value} is not a gender"}
  validate :user_exists?

  belongs_to(
    :owner,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id
  )

  has_many :cat_rental_requests,
    dependent: :destroy,
    class_name: 'CatRentalRequest',
    foreign_key: :cat_id,
    primary_key: :id

  def age
    ((Time.now - birth_date.to_time) / 1.year).floor
  end

  def user_exists?
    user = User.find(user_id)
    if user.nil?
      errors[:cat] << "Owner needs to exist"
    end
  end

end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  validates :cat_id, :start_date, :end_date, :status, :user_id, presence: true
  validates :status, inclusion: { in: %w(PENDING APPROVED DENIED), message: "%{value} is not a status"}
  validate :any_overlapping_requests?
  validate :user_exists?


  belongs_to :cat,
    class_name: 'Cat',
    foreign_key: :cat_id,
    primary_key: :id

  belongs_to :requester,
    class_name: 'User',
    foreign_key: :user_id,
    primary_key: :id


  def overlapping_requests
    # !(self.end_date < rental.start_date || rental.end_date < self.start_date)
    result = CatRentalRequest
      .where("cat_id = ?", self.cat_id)
      .where.not("start_date > ? OR end_date < ?", self.end_date, self.start_date)

    if self.persisted?
      result = result.where("id != ?", self.id)
    end

    result
  end

  def overlapping_approved_requests
    overlapping_requests.where(status: "APPROVED")
  end

  def any_overlapping_requests?
    unless overlapping_approved_requests
      errors.add(:cat_rental_request, "cannot overlap approved requests")
    end
  end

  def overlapping_pending_requests
    overlapping_requests.where(status: "PENDING")
  end

  def approve!
    self.transaction do
      if self.pending?
        self.update!(status: 'APPROVED')
        overlapping_pending_requests.each do |request|
          request.deny!
        end
      end
    end
  end

  def deny!
    self.update!(status: "DENIED")
  end

  def pending?
    self.status == 'PENDING'
  end

  def user_exists?
    user = User.find(user_id)
    if user.nil?
      errors[:cat_rental_request] << "Requester needs to exist"
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :user_name, :password_digest, :session_token, uniqueness: true, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  has_many(
    :cats,
    class_name: "Cat",
    foreign_key: :user_id,
    primary_key: :id
  )

  has_many :requests,
    class_name: 'CatRentalRequest',
    foreign_key: :user_id,
    primary_key: :id

  attr_reader :password

  def self.find_by_credentials(user_name, password)
    user = User.find_by(user_name: user_name)
    return nil if user.nil?

    user.is_password?(password) ? user : nil

  end

  def self.find_by_token(token)
    user = User.find_by_session_token(token)
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    self.save!
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    token = session[:session_token]
    return nil if self.session[:session_token].nil?
    @user ||= User.find_by_token(token)
  end

  def login_user!(user)
    user.reset_session_token!
    self.session[:session_token] = user.session_token
  end

  def user_signed_in
    redirect_to cats_url unless current_user.nil?
  end



end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

  def index
    @requests = CatRentalRequest.all
    render :index
  end

  def new
    @cats = Cat.all
    render :new
  end

  def create
    @request = CatRentalRequest.new(rental_params)

    if current_user.nil?
      # error[:cat] << "You need to be logged in"
      redirect_to new_session_url
      return
    end
    @request.user_id = current_user.id

    if @request.save
      redirect_to cat_url(@request.cat_id)
    else
      render json: @request.errors.full_messages, status: :unprocessable_entity
    end
  end

  def approve
    @request = CatRentalRequest.find(params[:cat_rental_request_id])
    @request.approve!
    redirect_to cat_url(@request.cat_id)
  end

  def deny
    @request = CatRentalRequest.find(params[:cat_rental_request_id])
    @request.deny!
    redirect_to cat_url(@request.cat_id)
  end


  private
  def rental_params
    params.require(:cat_rental_request).permit(:cat_id, :start_date, :end_date)
  end


end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    if current_user.nil?
      # error[:cat] << "You need to be logged in"
      redirect_to new_session_url
      return
    end
    @cat.user_id = current_user.id
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render json: @cat.errors.full_messages, status: :unprocessable_entity
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])
    @cat.update(cat_params)
    redirect_to cat_url(@cat)
  end

  private
  def cat_params
    params.require(:cat).permit(:birth_date, :color, :name, :sex, :description)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :user_signed_in, only: [:new, :create]

  def new
    render :sign_in
  end

  def create
    # fail
    @user = User.find_by_credentials(user_params[:user_name], user_params[:password])
    if @user.nil?
      redirect_to new_session_url
      return
    end
    login_user!(@user)

    if @user.save
      redirect_to cats_url
    else
      redirect_to new_session_url
    end
  end

  def destroy
    unless current_user.nil?
      current_user.reset_session_token!
    end

    session[:session_token] = nil
    redirect_to cats_url
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :user_signed_in, only: [:new, :create]

  def new
    # @user = User.find(params[:id])
    render :new
  end

  def create
    @user = User.new(user_params)
    login_user!(@user)
    if @user.save
      redirect_to cats_url
    else
      render json: @user.errors.full_messages, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cat_rental_requests/_form.html.erb
<form method="POST" action="<%= cat_rental_requests_url %>">
  <label>cats
    <select name="cat_rental_request[cat_id]">
    <% cats.each do |cat| %>
      <option value="<%= cat.id %>"><%= cat.name %></option>
    <% end %>
    </select>
  </label>

  <label for="cat-start-date">rental start date</label>
  <input type="date" id="cat-start-date" name="cat_rental_request[start_date]">

  <label for="cat-end-date">rental end date</label>
  <input type="date" id="cat-end-date" name="cat_rental_request[end_date]">

  <button type="submit">Submit Rental Request</button>

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">
</form>

app/views/cat_rental_requests/new.html.erb
<h2> New Rental Request </h2>

<%= render partial: "form" , locals: { cats: Cat.all }%>

app/views/cats/_form.html.erb
<form method="POST" action="<%= cat.persisted? ? cat_url(cat) : cats_url %>">
  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">
         
  <input type="hidden" name="_method" value="<%= cat.persisted? ? 'PATCH' : 'POST' %>" />
  <label for="cat-name">Cat name</label>
  <input type="text" id="cat-name" name="cat[name]" value="<%= cat.name %> ">

  <label for="cat-color">cat color</label>
  <select id="cat-color" name="cat[color]">
    <option selected disabled><%= cat.color%></option>
    <option value="Red">Red</option>
    <option value="Blue">Blue</option>
    <option value="Brown">Brown</option>
    <option value="White">White</option>
  </select>

  <label for="cat-sex-m">male</label>
  <input type="radio" id="cat-sex-m" name="cat[sex]" value="M" <%= "checked" if cat.sex == "M" %>>

  <label for="cat-sex-f">female</label>
  <input type="radio" id="cat-sex-f" name="cat[sex]" value="F" <%= "checked" if cat.sex == "F" %>>

  <label for="cat-birthdate">cat birthdate(YYYY-MM-DD)</label>
  <input type="date" id="cat-birthdate" name="cat[birth_date]" value="<%= cat.birth_date %>">

  <label for="cat-description">cat description</label>
  <textarea id="cat-description" name="cat[description]"><%= cat.description %></textarea>

  <button type="submit">Generate Cat!</button>
</form>

app/views/cats/edit.html.erb
<h2> Edit Cat </h2>

<%= render partial: "form", locals: { cat: @cat } %>

app/views/cats/index.html.erb
<h2>Cats</h2>

<ul>
  <% @cats.each do |cat| %>
    <li><%= cat.inspect %>
    <%= link_to "Show Cat", cat_url(cat.id) %> </li>
  <% end %>
</ul>

<%= link_to "Create new cat", new_cat_url %>

app/views/cats/new.html.erb
<h2> New Cat </h2>

<%= render partial: "form", locals: { cat: Cat.new } %>

app/views/cats/show.html.erb
<h2>Show Cat</h2>

<table>
  <tr>
    <td>Name</td>
    <td>Color</td>
    <td>Sex</td>
    <td>Age</td>
    <td>Description</td>
  </tr>
  <tr>
    <td><%= @cat.name %></td>
    <td><%= @cat.color %></td>
    <td><%= @cat.sex %></td>
    <td><%= @cat.age %></td>
    <td><%= @cat.description %></td>
  </tr>
</table>

Rental Requests
<table>
  <tr>
    <td>Start Date</td>
    <td>End Date</td>
    <td>Requester</td>
  </tr>
  <% @cat.cat_rental_requests.includes(:requester).order(:start_date).each do |request| %>
  <tr>
    <td><%= request.start_date %></td>
    <td><%= request.end_date %></td>
    <td><%= request.requester.user_name %></td>
    <% if !current_user.nil? && request.pending? && current_user.id == @cat.user_id %>
    <td>
      <form method="POST" action="<%= cat_rental_request_approve_url(request) %>">
        <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">
        <input type="hidden" name="_method" value="PATCH">
        <input type="submit" value="Approve">
      </form>
    </td>
    <td>
      <form method="POST" action="<%= cat_rental_request_deny_url(request) %>">
        <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">
        <input type="hidden" name="_method" value="PATCH">
        <input type="submit" value="Deny">
      </form>
    </td>
    <% end %>
  </tr>
  <% end %>
</table>

<%= link_to "All Cats", cats_url %>
<a href="<%= new_cat_rental_request_url %>">Request a cat</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CatRentals</title>
</head>
<body>
<% if current_user.nil? %>
 <a href="<%= new_session_url %>">Log in</a>
 <a href="<%= new_user_url %>">Sign up</a>
<% else %>
<%= current_user.user_name %>
  <form action="<%= session_url %>" method="post">
    <input type="hidden"
     name="authenticity_token"
     value="<%= form_authenticity_token %>">
    <input name="_method" type="hidden" value="delete" />
    <button name="button">log out</button>
  </form>
<% end %>


<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h2>Sign Up</h2>
<br>

<form method="POST" action="<%= users_url %>">
  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">
  <label>User Name
    <input type="text" name="user[user_name]">
  </label>

  <label>Password
    <input type="password" name="user[password]">
  </label>
  <button type="submit">Sign Up</button>
</form>